site_name: mkdocs-badges

theme:
  name: material
  features:
    - content.code.copy
    - navigation.footer
nav:
# Hide the index page -> would otherwise result in two mkdocs-badges links
- "": index.md

plugins:
- search
- crosslink:
    crosslinks:
    - name: alpha
      source_dir: site_a/docs
      target_url: http://localhost:8000/site_a/
      use_directory_urls: False
    # For causing errors (ambiguous protocol), do not do this in reallity
    - name: "alpha:2"
      source_dir: site_a/docs
      target_url: http://two.localhost:8000/site_a/
      use_directory_urls: True
    - name: "bravo"
      source_dir: site_b/docs
      target_url: http://localhost:8000/site_b
      use_directory_urls: True


# SEE https://squidfunk.github.io/mkdocs-material/reference/admonitions/
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
