site_name: mkdocs-badges

theme:
  name: material
  features:
    - content.code.copy
    - navigation.footer
nav:
# Hide the index page -> would otherwise result in two mkdocs-badges links
- "": index.md

plugins:
- search
- crosslink:
    crosslinks:
    - name: alpha
      source_dir: site_a/docs
      target_url: https://example.com/
      directory_urls: True

# SEE https://squidfunk.github.io/mkdocs-material/reference/admonitions/
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
